config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :trips, only: [:index, :new, :create, :show] do
    resources :invites, only: [:new, :create]
    patch '/invites/:id', to: 'invites#accept', as: :invite
  #   patch '/trips/:trip_id/invites/:id', to: 'invites#accept'
    resources :propositions, only: [:new, :create, :show, :destroy]
  end
  patch '/propositions/:id', to: 'propositions#validate', as: :validate
  patch '/propostitions/:id', to: 'propositions#book', as: :book
  resources :invites, only: [:index]
  # patch '/propositions/:id/dismiss', to: 'propositions#dismiss'
  resources :propositions, only: [:edit ] do
    resources :votes, only: [:new, :create]
    member do
      get :validate
      get :book
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/invite.rb
class Invite < ApplicationRecord
  belongs_to :trip
  belongs_to :user

  attr_accessor :email
end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController
 #Richad a code trop vite ce controller
 protect_from_forgery with: :null_session

  def index
    @invites = policy_scope(Invite).select {|invite| invite.user_id == current_user.id}
    @pending_invites = @invites.select {|invite| invite.accepted.nil?}.uniq
    @accepted_invites = @invites.select {|invite| invite.accepted?}.uniq
  end

  def new
    @invite = Invite.new
    @trip = Trip.find(params[:trip_id])
  end

  def create
    @invite = Invite.new(invite_params)
    @trip = Trip.find(params[:trip_id])
    @invite.trip = @trip
    #Getting email from form
    email = params[:invite][:email]
    #Getting user from email submitted by the user
    user = User.find_by(email: email)
    authorize @invite
    if user
      @invite.user = user
    end
    if @invite.save
      flash.notice = "#{@invite.user.first_name} has been invited to #{@invite.trip.title}"
    else
      flash.alert = "#{email} doesn't have a Friends Trip account yet."

    end
    redirect_to trip_path(@trip.id)
  end

  def accept
    # raise
    @invite = Invite.find(params[:id])
    @invite.accepted = true
    authorize @invite
    if @invite.save
      flash.notice = "You successfully joined #{@invite.trip.title}"
      redirect_to trip_path(@invite.trip)
    end
  end

  private

  def invite_params
    params.require(:invite).permit(:trip_id)
  end
end

app/views/invites/_invite_card.html.erb
<div class="row" >
  <% invites.each do |invite| %>
        <div class="col-6">

          <%= link_to trip_path(invite.trip), class: "trip-card-link", data: {turbolinks: false} do%>
            <div class="trip-card" >
              <div class="trip-card-top <%= invite.trip.destination %>">
                <div class="avatar-card">
                  <% if invite.trip.user.avatar.attached? %>
                    <p><%= cl_image_tag invite.trip.user.avatar.key, width: 50, height: 50, crop: :fill, style: "border-radius: 50%;", class: "image" %></p>
                  <% else %>
                    <%= image_tag("avatar.png", width: 50, height: 50, crop: :fill, style: "border-radius: 50%;", class: "image") %>
                  <% end %>
                  <div class="middle">
                    <div class="text">
                      <%= invite.trip.user.first_name %>
                    </div>
                  </div>
                </div>
                <h3><%= invite.trip.title %></h3>
                <%= invite.trip.destination %>
              </div>
              <div class="trip-card-bottom">
                <div class="trip-card-date">
                <div class="start-date"> <i class="fas fa-plane-departure"></i> <%= "#{invite.trip.start_date.strftime("%d %b %Y")}"%> </div>
                <div class="end-date"> <i class="fas fa-plane-arrival"></i> <%= "#{invite.trip.end_date.strftime("%d %b %Y")}"%> </div>
                </div>
                <% if invite.accepted.nil? %>
                  <div class="accept-invite">
                    <%= link_to trip_invite_path(invite.trip.id, invite.id), remote: true, method: :patch do %>
                      <span class='button-interactive invite-button'>Accept</span>
                    <% end %>
                  </div>
                <% end %>
                <div class="trip-days">
                <%# <span class="month"> <#%= "from #{trip.start_date.strftime("%b %d, %Y")} to #{trip.end_date.strftime("%b %d, %Y")}"%>
                <div class="duration"><i class="far fa-clock"></i> Duration:<div class="data"> <%= "#{pluralize (invite.trip.end_date - invite.trip.start_date).to_i, "day"}" %></div> </div>
                <div class="participating"><i class="fas fa-user-check"></i>Participating:<div class="data"> <%= "#{invite.trip.users.count + 1}" %> </div> </div>
              </div>
                <div class="trip-invitees">
                  <% invite.trip.invites.each do |invite| %>
                    <% if invite.user.avatar.attached? %>
                      <%= cl_image_tag invite.user.avatar.key, width: 30, height: 30, crop: :fill, class: "trip-invitee" %>
                    <% else %>
                      <%= image_tag("avatar.png", class: "trip-invitee") %>
                    <% end %>
                  <% end %>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
</div>

app/views/invites/_new_invite_modal.html.erb
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered offset-top-modal modal-trip-show" role="document">
    <div class="modal-content modal-trip-show-radius">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Invite a friend to join <%=@trip.title%></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span class="close-invite"aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= simple_form_for [@trip, @invite], remote: true do |f| %>
      <div class="modal-body">
        <div class="form-wrapper" id="invite-form-div">
          <%= f.input :email, label: 'Please enter an email address to invite a friend', :placeholder => 'friend@friendtrip.com' %>
        </div>
      </div>
      <div class="modal-footer">
        <%= f.button :submit, 'Send invite', class: "button-orange" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/invites/index.html.erb
<div class="banner " style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)),url(https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1008&q=80 );">
  <div>
    <div class="container text-center">
      <div class="index-title mb-5">
        <h1>Your invites</h1>
      </div>
      <div>
        <%= link_to  "Add a trip", new_trip_path, class: "button-orange" %>
      </div>
      <div class="row d-flex text-end">
        <div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="mt-2 user-invites container">

  <div class="row">
    <% if @pending_invites.count == 0 %>
      <p> You have no pending invites... Maybe you should go back to <%= link_to "your trips", trips_path %></p>
    <% else %>
      <h2>My pending invites <%= "(#{@pending_invites.count})" %> </h2>
      <div class="container">
        <%= render "invite_card", invites: @pending_invites.uniq %>  
      </div>
    <% end %>
  </div>
</div>

app/views/invites/new.html.erb
<!-- Use in a modal in the show trip page -->

<h1>Create an invite for your @trip.title trip</h1>

<div class="container">
  <div class="form-wrapper" id="invite-form-div">
    <%= simple_form_for [@trip, @invite] do |f| %>
      <%= f.input :email %>
      <%= f.submit %>
    <% end %>
  </div>
</div>