config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :trips, only: [:index, :new, :create, :show] do
    resources :invites, only: [:new, :create]
    patch '/invites/:id', to: 'invites#accept', as: :invite
  #   patch '/trips/:trip_id/invites/:id', to: 'invites#accept'
    resources :propositions, only: [:new, :create, :show, :destroy]
  end
  patch '/propositions/:id', to: 'propositions#validate', as: :validate
  patch '/propostitions/:id', to: 'propositions#book', as: :book
  resources :invites, only: [:index]
  # patch '/propositions/:id/dismiss', to: 'propositions#dismiss'
  resources :propositions, only: [:edit ] do
    resources :votes, only: [:new, :create]
    member do
      get :validate
      get :book
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/proposition.rb
class Proposition < ApplicationRecord
  belongs_to :trip
  belongs_to :user
  has_many :votes, dependent: :destroy
  has_many :users, through: :votes

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  validates :category, :start_date, :end_date, :address, presence: true
  ICONS = {
    "food" => "fa-hamburger",
    "activity" => "fa-volleyball-ball",
    "accomodation" => "fa-bed"}
end

app/controllers/propositions_controller.rb
class PropositionsController < ApplicationController

  def show
    @proposition = Proposition.find(params[:trip_id])
    authorize @proposition
  end

   def new
     @proposition = Proposition.new
     @trip = Trip.find(params[:trip_id])
     authorize @proposition
   end

  def create
    @proposition = Proposition.new(proposition_params)
    @proposition.user_id = current_user.id
    @trip = Trip.find(params[:trip_id])
    @proposition.trip_id = @trip.id
    authorize @proposition
    if @proposition.save
      flash.notice = "#{@proposition.title} has been added to pending propositions"
      redirect_to trip_path(@trip.id, anchor: "prop-#{@proposition.id}")
    else
      render :new
    end
  end

  def validate
    @proposition = Proposition.find(params[:id])
    @proposition.status = "validated"
    authorize @proposition
    if @proposition.save
    flash.notice = "#{@proposition.title} has been moved to validated steps."
    redirect_to trip_path(@proposition.trip, anchor: "prop-#{@proposition.id}")
    end
  end

  def destroy
    @proposition = Proposition.find(params[:trip_id])
    @proposition.destroy
    flash.notice = "#{@proposition.title} has been removed."
    redirect_to trip_path(@proposition.trip)
    authorize @proposition
  end

  def book
    @proposition = Proposition.find(params[:id])
    @proposition.booked = true
    authorize @proposition
    if @proposition.save
      flash.notice = "#{@proposition.trip.title} has been moved to trip details."
      redirect_to trip_path(@proposition.trip, anchor: "prop-#{@proposition.id}")
    end
  end



  #  def markers(prop)
  #   @trip = Trip.find(params[:id])
  #   @propositions = @trip.propositions
  #   @pending_prop = @propositions.select {|prop| prop.status =! "validated"}
  #   @validated_prop = @propositions.select {|prop| prop.status == "validated"}
  #   if prop = "pending"
  #     @markers = @pending_propositions.geocoded.map do |proposition|
  #       {
  #         lat: proposition.latitude,
  #         lng: proposition.longitude,
  #         info_window: render_to_string(partial: "info_window", locals: { proposition: proposition }),
  #         marker_icon: '<i class="fas <%=iconecategory%>"></i>',
  #         marker_color: "text-color-#{proposition.category}"
  #       }
  #     end
  #   else
  #     @markers = @validated_prop.geocoded.map do |proposition|
  #       {
  #         lat: proposition.latitude,
  #         lng: proposition.longitude,
  #         info_window: render_to_string(partial: "info_window", locals: { proposition: proposition }),
  #         marker_icon: '<i class="fas <%=iconecategory%>"></i>',
  #         marker_color: "text-color-#{proposition.category}"
  #       }
  #     end
  #   end
  #  end


  private

  def proposition_params
    params.require(:proposition).permit(:trip_id, :user_id, :category, :start_date, :end_date, :due_date, :title, :description, :url, :address)
  end

end

app/views/propositions/_avatar_on_cards.html.erb
<div class="trip-owner-show">
  <!-- The code below displays the photo of the owner of the trip. I disabled it cause of responsivenss -->
  <!-- <% if @trip.user.avatar.attached? %>
    <p><%= cl_image_tag @trip.user.avatar.key, width: 100, height: 100, crop: :fill, style: "border-radius: 50%;", class: "image" %></p>
  <% else %>
    <%= image_tag("avatar.png", class: "trip-owner-show image") %>
  <% end %> -->
</div>

<div class="trip-invitees-show ">
 <div class="button-add-invites " data-toggle="modal" data-target="#exampleModal">
    <div data-toggle="tooltip" data-placement="top" title="Invite a friend" class="tooltip-add">
      <i class="fas fa-plus"></i>
    </div>
  </div>
  <% @trip.invites.each do |invite| %>
  <div class="position-relative">
    <div class="">
      <% if invite.user.avatar.attached? %>
        <% if invite.accepted?%>
          <%= cl_image_tag invite.user.avatar.key, width: 50, height: 50, crop: :fill, class: "trip-invitee-show" %>
        <% else %>
          <%= cl_image_tag invite.user.avatar.key, width: 50, height: 50, crop: :fill, class: "trip-invitee-show unaccepted-invite"%>
        <% end %>
      <% else %>
        <%= image_tag("avatar.png", class: "trip-invitee-show") %>
      <% end %>
    </div>
    <div class="avatar-card-name">
      <%= invite.user.first_name %>
    </div>
  </div>
  <% end %>
</div>

app/views/propositions/_button_dislike_vote.html.erb
<div class = "mx-2">
  <% if proposition.votes.where(status: 'downvote').map {|vote| vote.user}.include?(current_user) %>
    <i class='far fa-thumbs-down user-voted' data-target="#dislikeModal-<%=proposition.id%>" data-toggle="modal"></i>
  <% else %>
    <% if proposition.votes.where(status: 'upvote').map {|vote| vote.user}.include?(current_user) %>
      <i class='far fa-thumbs-down unactive-vote' data-target="#dislikeModal-<%=proposition.id%>" data-toggle="modal"></i>
    <% else %>
      <i class='far fa-thumbs-down unvoted' data-target="#dislikeModal-<%=proposition.id%>" data-toggle="modal"></i>
    <% end %>
  <% end %>
  <span class="vote-counter">
    <%=proposition.votes.select {|vote| vote.status == "downvote"}.count%>
  </span>
</div>

app/views/propositions/_button_like_vote.html.erb
<div class="mx-2">
  <% if proposition.votes.where(status: 'upvote').map {|vote| vote.user}.include?(current_user) %>
    <i class='far fa-thumbs-up user-voted' data-target="#likeModal-<%=proposition.id%>" data-toggle="modal"></i>
  <% else %>
    <% if proposition.votes.where(status: 'downvote').map {|vote| vote.user}.include?(current_user) %>
      <i class='far fa-thumbs-up unactive-vote' data-target="#likeModal-<%=proposition.id%>" data-toggle="modal"></i>
    <% else %>
      <i class='far fa-thumbs-up unvoted' data-target="#likeModal-<%=proposition.id%>" data-toggle="modal"></i>
    <% end %>
  <% end %>
  <span class="vote-counter">
    <%=proposition.votes.select {|vote| vote.status == "upvote"}.count%>
  </span>
</div>

app/views/propositions/_dislike_modal_form.html.erb
<!-- This is the modal form for a dislike, used on a proposition card in _list -->
<div class="modal " id="dislikeModal-<%=proposition.id%>" tabindex="-1" role="dialog" aria-labelledby="dislikeModalLabel-<%=proposition.id%>" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-trip-show-radius"   role="document">
    <div class="modal-content" style="border-radius: 15px">
      <div class="modal-header">
        <h5 class="modal-title" id="dislikeModalLabel-<%=proposition.id%>">Downvote <%=proposition.title%> ?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= simple_form_for [proposition, vote], remote: true do |f| %>
        <div class="modal-body">
          <div class="form-wrapper">
            <% if proposition.users.include?(current_user) %>
              <%= f.input :comment, disabled: true %>
            <% else %>
              <%= f.input :comment %>
            <% end %>
              <%= f.input :status, as: :hidden, :input_html => { :value =>  "downvote" } %>
          </div>
        </div>
        <div class="modal-footer">
          <div type="button" class="button-green" data-dismiss="modal">
            Cancel
          </div>
          <% if proposition.users.include?(current_user) %>
            <%= f.button :submit, 'Already voted', class: "button-orange d-none" %>
            <div class = 'btn btn-disabled'>
              You already voted!
            </div>
          <% else %>
            <%= f.button :submit, 'downvote', class: "button-orange" %>
          <% end %>
        </div>
      <% end %>
      </div>
    </div>
  </div>

app/views/propositions/_info_window.html.erb
<h2><%= proposition.title %></h2>
<p><%= proposition.address %></p>

app/views/propositions/_like_modal_form.html.erb
<!-- This is the modal form for a like, used on a proposition card in _list -->

<div class="modal " id="likeModal-<%=proposition.id%>" tabindex="-1" role="dialog" aria-labelledby="likeModalLabel-<%=proposition.id%>" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-trip-show-radius"  role="document">
    <div class="modal-content" style="border-radius: 15px">
      <div class="modal-header">
        <h5 class="modal-title" id="likeModalLabel-<%=proposition.id%>">Upvote <%=proposition.title%> ?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= simple_form_for [ proposition, vote ], remote: true, method: :post do |f| %>
        <div class="modal-body">
          <div class="form-wrapper">
            <%= f.input :comment %>
            <%= f.input :status, as: :hidden, :input_html => { :value =>  "upvote" } %>
          </div>
        </div>
        <div class="modal-footer">
          <div type="button" class="button-green" data-dismiss="modal">Cancel</div>
          <% if proposition.users.include?(current_user) %>
            <%= f.button :submit, 'Already voted', class: "button-orange d-none" %>
            <div class = 'btn btn-disabled'>
              You already voted!
            </div>
          <% else %>
            <%= f.button :submit, 'Upvote', class: "button-orange" %>
          <% end %>
        </div>
        <% end %>
    </div>
  </div>
</div>

app/views/propositions/_list.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-sm-12">
      <div class="list-propositions ">
        <% propositions.each do |proposition| %>
        <div class="prop-card global-card-proposition<%= 'validated-prop' if proposition.status == 'validated'%> <%= proposition.category %>" id="prop-<%= proposition.id %>">
        <!--top card -->
          <div class="card-proposition-top bg-color-<%= proposition.category %>">
            <!-- BUTTON DELETE -->
            <% if policy(proposition).destroy? %>
              <%= link_to trip_proposition_path(proposition),
                  method: :delete,
                  class: "delete-prop",
                  data: { confirm: "Are you sure you want to delete this proposition?" } do %>
              <span class="button-delete">
              <i class="fas fa-trash-alt"></i>
              </span>
              <% end %>
            <% end %>

            <h4 data-toggle="modal" data-target="#propositionShow-<%= proposition.id %>" class="proposition-title">
              <%= proposition.title %>
            </h4>
            <p class="prop-by">by <%=proposition.user.first_name%></p>
            <!--category -->
            <p class="badge-category">
            <i class="fas <%=Proposition::ICONS[proposition.category]%> "></i>
            <%= proposition.category %>
            </p>
          </div>
            <!--bottom card -->
          <div class="card-proposition-bottom">
            <p><i class="fas fa-stopwatch mr-2"></i>Due date: <%= proposition.due_date.strftime("%B %d, %Y") if proposition.due_date %></p>
            <% if proposition.start_date != proposition.end_date %>
              <p><i class="fas fa-calendar-alt mr-2"></i><%= "#{proposition.start_date.strftime("%D")} to #{proposition.end_date.strftime("%D")}"%></p>
            <% else %>
              <p><i class="fas fa-calendar-alt mr-2"></i><%=" #{proposition.start_date.strftime("%D") if proposition.start_date}" %> </p>
            <% end %>
            <div class="prop-votes">
              <!-- Button trigger like vote -->
              <%= render 'propositions/button_like_vote', proposition: proposition %>

              <!-- Button trigger dislike vote -->
              <%= render 'propositions/button_dislike_vote', proposition: proposition %>
            </div>

            <div class="validation-prop">
              <% if proposition.status != 'validated' %>
              <% end %>
              <% if proposition.status != 'validated' && proposition.trip.user == current_user %>
                <%= link_to validate_path(proposition), remote: true, method: :patch do %>
                  <span class='button-interactive'>validate</span>
                <% end %>
              <% elsif proposition.status == 'validated'%>
                <span class='button-validated'>VALIDATED</span>
              <% end %>
                
              <% if proposition.booked != true && proposition.trip.user == current_user && proposition.status == "validated" %>
                <%= link_to book_path(proposition), remote: true, method: :patch do %>
                  <span class='button-interactive-book'>BOOK</span>
                <% end %>
              <% elsif proposition.booked == true %>
                <span class='button-booked'>BOOKED</span>
              <% end %>
            </div>
          </div>
        </div>
        <!-- Modal show of the proposition, with comments & votes  -->
        <%= render 'propositions/proposition_modal', proposition: proposition %>

        <!-- Like modal form -->
        <%= render 'propositions/like_modal_form', proposition: proposition , vote: @vote %>

        <!-- disLike modal form -->
         <%= render 'propositions/dislike_modal_form', proposition: proposition , vote: @vote %>

        <% end %>
      </div>
    </div>

    <div class="col-md-4 col-sm-12 ">
      <div class="map" id="<%= map %>" style = "  width: 100%;
        height: 100vh; 
        border-radius: 20px;"
        data-markers="<%= markers %>"
        <% if local_assigns[:steps] %>
          data-steps="<%= steps.to_json %>"
        <% end %>
        data-mapbox-api-key="<%=ENV['MAPBOX_API_KEY']%>">
      </div>
    </div>
  </div>
</div>

app/views/propositions/_new_proposition_modal.html.erb
<div class="modal fade w-100" id="propositionModal" tabindex="-1" role="dialog" aria-labelledby="propositionModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-proposition-new" role="document">
    <div class="modal-content modal-proposition-new-style">
      <%# <div class="modal-header">
        <h5 class="modal-title" id="propositionModalLabel">Submit your proposition</h5>
      </div> %>
      <%= simple_form_for [@trip, @proposition], remote: true do |f| %>
      <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">
      <div class="modal-body">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <div class="form-wrapper proposition-form d-flex justify-content-between booking-form-div-proposition" id="booking-form-div">
          <div class="container">
            <div class="row">
              <div class="col-md-6 col-sm-12">

                
                
                <div class="proposition-form-left">
                  <%= f.input :category, :collection => ["food", "accomodation", "activity"], label: 'Pick a category'%>
                  <%= f.input :address, as: :string, :placeholder => '96 Rue Saint-Maur, 75011 Paris' %>
                  <%= f.input :title, :placeholder => "L'Alicheur" %>
                  <%= f.input :description, :placeholder => "Great restaurant for lunch" %>
                  <%= f.input :url, :placeholder => "wwww.restaurantwebsite.com" %>
                </div>
              </div>
              <div class="col-md-6 col-sm-12">

                <div class="proposition-form-right">
                  <%= f.input :start_date, label: "Select dates:", as: :string, required: false, input_html: { id: "range_start", class: "d-none flatpickr-date-prop" } %>
                  <%= f.input :end_date, label: false, as: :string, required: false, input_html: { id: "range_end", class: "d-none"  } %>
                  <%= f.input :due_date %>
                </div>
              </div>
              </div>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <div class="">
            <%= f.button :submit, 'Add proposition', class: "button-orange" %>
          </div>
        </div>
        <% end %>
    </div>
  </div>
</div>

app/views/propositions/_nnew_proposition_modal.html.erb
<div class="modal fade w-100" id="propositionModal" tabindex="-1" role="dialog" aria-labelledby="propositionModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-proposition-new" role="document">
    <div class="modal-content modal-proposition-new-style">
      <%# <div class="modal-header">
        <h5 class="modal-title" id="propositionModalLabel">Submit your proposition</h5>
      </div> %>
      <%= simple_form_for [@trip, @proposition], remote: true do |f| %>
      <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">
      <div class="modal-body">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <div class="form-wrapper proposition-form d-flex justify-content-between booking-form-div-proposition" id="booking-form-div">
          <div class="container">
            <div class="row">
              <div class="col-md-6 col-sm-12">

                
                
                <div class="proposition-form-left">
                  <%= f.input :category, :collection => ["food", "accomodation", "activity"], label: 'Pick a category'%>
                  <%= f.input :address, as: :string, :placeholder => '96 Rue Saint-Maur, 75011 Paris' %>
                  <%= f.input :title, :placeholder => "L'Alicheur" %>
                  <%= f.input :description, :placeholder => "Great restaurant for lunch" %>
                  <%= f.input :url, :placeholder => "wwww.restaurantwebsite.com" %>
                </div>
              </div>
              <div class="col-md-6 col-sm-12">

                <div class="proposition-form-right">
                  <%= f.input :start_date, label: "Select dates:", as: :string, required: false, input_html: { id: "range_start", class: "d-none flatpickr-date-prop" } %>
                  <%= f.input :end_date, label: false, as: :string, required: false, input_html: { id: "range_end", class: "d-none"  } %>
                  <%= f.input :due_date %>
                </div>
              </div>
              </div>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <div class="">
            <%= f.button :submit, 'Add proposition', class: "button-orange" %>
          </div>
        </div>
        <% end %>
    </div>
  </div>
</div>

app/views/propositions/_proposition_modal.erb
<div class="modal" id="propositionShow-<%= proposition.id %>" tabindex="-1" role="dialog" aria-labelledby="propositionShowModalLabel-<%= proposition.id %>" aria-hidden="true">

  <div class="modal-dialog-centered w-75 mx-auto mt-5 modal-trip-show" role="document">
    <div class="modal-content modal-trip-show-radius">
      <div class="modal-header bg-color-<%= proposition.category %>">
        <div class="modal-prop-title ">
          <h5 class="modal-title proposition-title" id="propositionShowModalLabel-<%= proposition.id %>"><%= link_to "#{proposition.title}", proposition.url, target: "_blank" %></h5>
        </div>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="modal-prop-counter-proposition">
          <p><mark style="color:green"><%= pluralize proposition.votes.select{ |vote| vote.status == "upvote" }.count,"" %><i class="fas fa-thumbs-up"></i></mark></p>
          <p><mark style="color: red"><%= pluralize proposition.votes.select{ |vote| vote.status == "downvote" }.count, "" %><i class="fas fa-thumbs-down"></i></mark></p>
        </div>
        <div class="modal-prop-description bg-light">
          <p><ins>Description:</ins></p>
          <p><em><%= proposition.description %></em></p>
        </div>
        <div class="modal-prop-comments">
          <p><ins><%=  pluralize proposition.votes.select {|vote| vote.comment !=""}.count, "comment" %></ins> :</p>
          <% proposition.votes.each do |vote|%>
            <% if vote.comment != "" %>
            <div class="comment">
              <p class="name"><%= vote.user.first_name %>:</p>
              <p class="content">"<%= vote.comment %>"</p>
            </div>
            <% end %>
          <% end %>
        </div>
      </div>
      <div class="modal-footer">
        <% if proposition.status != 'validated' && proposition.trip.user == current_user %>
            <%= link_to validate_path(proposition), remote: true, method: :patch do %>
              <span class='button-interactive'>validate</span>
            <% end %>
            <% else %>
                <p class='validatedpropmsg'>validated</p>
            <% end %>
      </div>
    </div>
  </div>
</div>

app/views/propositions/new.html.erb
<%= render 'shared/navbar' %>
<!-- will be used in a modal in trip show -->

<%# <h1>Create a proposition for your @trip.title trip</h1> %>

<div class="container">
  <div class="form-wrapper" id="booking-form-div">
    <%= simple_form_for [@trip, @proposition] do |f| %>
      <%= f.input :category, :collection => ["food", "accomodation", "activity"], label: 'Pick a category' %>
      <%= f.input :start_date, label: "Sélectionnez vos dates:", as: :string, required: false, input_html: { id: "range_start", class: "d-none" } %>
      <%= f.input :end_date, label: false, as: :string, required: false, input_html: { id: "range_end", class: "d-none"  } %>
      <%= f.input :due_date %>
      <%= f.input :address %>
      <%= f.input :title %>
      <%= f.input :description %>
      <%= f.input :url %>
      <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/propositions/show.html.erb
<% content_for :meta_title, "#{@proposition.title} is on #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, @proposition.description %>

<div class="modal fade" id="propositionShow-<%= proposition.id %>" tabindex="-1" role="dialog" aria-labelledby="propositionShowModalLabel-<%= proposition.id %>" aria-hidden="true">


  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="propositionShowModalLabel-<%= proposition.id %>"><%= proposition.title %></h5>
        <br>
        <p>Upvote: <%= proposition.votes.select{ |vote| vote.status == "upvote" }.count %> times</p>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p><%= proposition.description %></p>
        <h6>Comments: </h6>
        <ul>
          <li><%= proposition.user.first_name %>: <%= proposition.user.votes.comment %></li>
        </ul>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Edit</button>
      </div>
    </div>
  </div>
</div>




<div class="modal " id="propositionShow-<%= proposition.id %>" tabindex="-1" role="dialog" aria-labelledby="propositionShowModalLabel-<%= proposition.id %>" aria-hidden="true">


  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <div class="modal-prop-title">
          <h5 class="modal-title text-center" id="propositionShowModalLabel-<%= proposition.id %>"><%= proposition.title %> (<%= link_to "link to Url", proposition.url %>)</h5>
        </div>

        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="modal-prop-counter pl-3 text-right">
          <p><mark>Upvoted: <%= proposition.votes.select{ |vote| vote.status == "upvote" }.count %> times</mark></p>
        </div>
        <div class="modal-prop-description bg-light pl-3">
          <p><ins>Description:</ins></p>
          <p>"<em><%= proposition.description %></em>"</p>
        </div>
        <div class="modal-prop-comments pl-3">
          <p><ins>Comments:</ins></p>
          <ul>
          <% proposition.votes.each do |vote|%>
            <li><p><%= vote.user.first_name %>: "<%= vote.comment %>"</p></li>
          <% end %>
          </ul>
        </div>
      </div>
      <div class="modal-footer">
        <span class="sign-button button-green" data-dismiss="modal">Close</span>
        <span class="sign-button button-orange">Edit</span>
      </div>
    </div>
  </div>
</div>