config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :trips, only: [:index, :new, :create, :show] do
    resources :invites, only: [:new, :create]
    patch '/invites/:id', to: 'invites#accept', as: :invite
  #   patch '/trips/:trip_id/invites/:id', to: 'invites#accept'
    resources :propositions, only: [:new, :create, :show, :destroy]
  end
  patch '/propositions/:id', to: 'propositions#validate', as: :validate
  patch '/propostitions/:id', to: 'propositions#book', as: :book
  resources :invites, only: [:index]
  # patch '/propositions/:id/dismiss', to: 'propositions#dismiss'
  resources :propositions, only: [:edit ] do
    resources :votes, only: [:new, :create]
    member do
      get :validate
      get :book
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer d-flex bottom">
  <div class="footer-links flex-grow-1 mr-4">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright flex-grow-2">
    This footer is made with <i class="fas fa-heart"></i> by the FriendsTrip team
  </div>
</div>

app/views/shared/_navbar.html.erb
<navbar class="navbar navbar-expand navbar-light navbar-lewagon fixed-top">
  <%= link_to root_path, class: "navbar-brand" do %>
    <img src="https://seeklogo.com/images/V/vw-combi-lateral-logo-D02777CEAE-seeklogo.com.png" alt="combi volkswagen"  width="500" class="facette"/>

    <strong class="logo-font">Friends-Trip</strong>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" aria-expanded="false" aria-label="Toggle navigation">
    <%= link_to root_path%>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav">
      <% if user_signed_in?%>
        <li class="nav-item ">
          <%= link_to  "Your trips", trips_path, class: "button-green-your-trips mr-3" %>
        </li>

        <li class="nav-item dropdown dropdown-logged ">

          <% if current_user.avatar.attached? %>
            <img class="avatar dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="<%= cl_image_path current_user.avatar.key %>" type="button"/>
          <% else %>
            <i class='fas fa-user-circle avatar dropdown-toggle' id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"type="button" ></i>
          <% end %>
          <%= "<i class='fas fa-dot-circle dot-invite'></i>".html_safe if current_user.invites.select {|invite| invite.accepted.nil?}.count!=0%>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <div class = "notification-invite">
              <%= link_to  "My invites", invites_path, class: "dropdown-item" %>
              <%= "<i class='fas fa-dot-circle'></i>".html_safe if current_user.invites.select {|invite| invite.accepted.nil?}.count!=0%>
            </div>
            <%= link_to  "Add a trip", new_trip_path, class: "dropdown-item" %>
            <a href="/trips" class="dropdown-item d-block your-trip-drop">Your trips</a>
            <%#= link_to  "Your trips", trips_path, class: "dropdown-item your-trip-item" %>
            <%= link_to "Edit your profile", edit_user_registration_path, class: "dropdown-item"  %>
            <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item dropdown">
          <i class="fas fa-user-circle avatar dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></i>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Sign in", user_session_path, class: "dropdown-item" %>
            <%= link_to "Sign up", new_user_registration_path, class: "dropdown-item" %>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</navbar>

app/views/shared/_todelete.html.erb
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
      <% if user_signed_in?%>
        <li class="nav-item ">
          <%= link_to  "Your trips", trips_path, class: "button-green" %>
        </li>


        <li class="nav-item dropdown active">
          <button class="btn btn-secondary dropdown-toggle" type="button" id="navbarDropdown" data-toggle="dropdown" aria-labelledby="navbarDropdown">
          Dropdown button
          </button>
          <%# <img class="avatar dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://kitt.lewagon.com/placeholder/users/ssaunier" role="button" /> %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to  "My invites", invites_path, class: "dropdown-item" %>
            <%= link_to  "Add a trip", new_trip_path, class: "dropdown-item" %>
            <%= link_to "Edit your profile", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </li>
      <% else %>
        <li class="nav-item dropdown">
          <i class="fas fa-user-circle avatar dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></i>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Sign in", user_session_path, class: "dropdown-item" %>
            <%= link_to "Sign up", new_user_registration_path, class: "dropdown-item" %>
          </div>
        </li>
      <% end %>